BookCollection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from profiles import urls as profiles_urls
from library import urls as library_urls
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(profiles_urls, namespace='profiles')),
    path('library/', include(library_urls, namespace='library')),
    path('', home_view),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),

]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import book_create_or_update_view, collection_view, book_view, book_delete

app_name = 'library'

urlpatterns = [
    path('book-create/', book_create_or_update_view, name='book-create'),
    path('book-update/<str:book_id>', book_create_or_update_view, name='book-update'),
    path("select2/", include("django_select2.urls")),
    path("collection/<str:collection_id>/", collection_view, name='book-list'),
    path("book/<collection_id>/<str:book_id>/", book_view, name='book'),
    path("book-delete/<collection_id>/<str:book_id>/", book_delete, name='book-delete')
]

profiles/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from .views import profile_view, profiles_list_view

app_name = 'profiles'

urlpatterns = [
    path('profile/<profile_id>/', profile_view, name='profile'),
    path('', profiles_list_view, name='profile-list'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
import datetime


class Profile(models.Model):
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=150, blank=True)
    avatar = models.CharField(default='https://i.ibb.co/tKtFPgr/blank-profile-picture-g9a1ddb035-640.png', max_length=300)
    following = models.ManyToManyField(User, blank=True, related_name='following')
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    slug = models.SlugField(unique=True, blank=True)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.created}"

    def get_my_books_number(self):
        collection = list(self.collection.filter(name="bookshelf"))
        try:
            return collection[0].get_books_number()
        except:
            return 'no date'

    def get_wish_list_books_number(self):
        collection = list(self.collection.filter(name="wish_list"))
        try:
            return collection[0].get_books_number()
        except:
            return 'no date'

    def get_favorites_books_number(self):
        collection = list(self.collection.filter(name="favorites"))
        try:
            return collection[0].get_books_number()
        except:
            return 'no date'

    def get_all_authors(self):
        return self.collection.values('books__authors__name')

    def get_author(self, name):
        collections = self.collection.all()

        for collection in collections:
            books = collection.books.all()
            for book in books:
                authors = book.authors.all()
                for author in authors:
                    if author.name == name:
                        return author

    def get_series(self, name):
        collections = self.collection.all()

        for collection in collections:
            books = collection.books.all()
            for book in books:
                try:
                    series = book.series.name
                    if series == name:
                        return book.series
                except:
                    pass

    def get_publisher(self, name):
        # print(name)
        collections = self.collection.all()

        for collection in collections:
            books = collection.books.all()
            for book in books:
                try:
                    publisher = book.publisher.name
                    if publisher == name:
                        return book.publisher
                except:
                    pass

    def get_collection(self, name):
        # print(name)
        return self.collection.get(name=name)

    def get_bookshelf(self):
        return self.get_collection('bookshelf')

    def get_wish_list(self):
        return self.get_collection('wish_list')

    def get_favorites(self):
        return self.get_collection('favorites')

    def get_authors_number_bookshelf(self):
        collection = list(self.collection.filter(name="bookshelf"))
        try:
            return collection[0].get_authors_number()
        except:
            return 'no date'

    def get_series_number_bookshelf(self):
        collection = list(self.collection.filter(name="bookshelf"))
        try:
            return collection[0].get_series_number()
        except:
            return 'no date'

    def get_publisher_number_bookshelf(self):
        collection = list(self.collection.filter(name="bookshelf"))
        try:
            return collection[0].get_publisher_number()
        except:
            return 'no date'

    def get_books_read_number_bookshelf(self):
        collection = list(self.collection.filter(name="bookshelf"))
        try:
            return collection[0].get_books_read_number()
        except:
            return 'no date'

    def get_followers(self):
        return self.followers.all()

    def get_following(self):
        return self.following.all()

    def get_followers_number(self):
        return self.followers.all().count()

    def get_following_number(self):
        return self.following.all().count()

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user.username)

        self.slug = to_slug
        self.update = datetime.datetime.now()
        super().save(*args, **kwargs)



class Follow(models.Model):
    follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='follower')
    followee = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='followee')
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.follower}-{self.followee}"

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    image = forms.FileField(required=False)

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ProfileModelForm, self).__init__(*args, **kwargs)

        self.fields['avatar'].required = False

profiles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Profile, Follow
from .forms import ProfileModelForm
import base64
import requests
from django.core.paginator import Paginator


def upload_file(image):
    response = requests.post("https://api.imgbb.com/1/upload",
                             data={'key': 'c46bc9a4a26941d4b62716eb03df3df8',
                                   'image': image,
                                   'expiration': 60
                                   })
    try:
        response.raise_for_status()
        geodata = response.json()
        return geodata['data']['thumb']['url']
    except requests.exceptions.HTTPError:
        errors = {}
        errors.setdefault('picture', []).append("Bad picture")
        return errors


def follows(request, profile, user_profile):
    if request.method == 'POST':
        follow = Follow.objects.filter(follower=user_profile, followee=profile)
        if follow:
            follow.delete()
        else:
            Follow.objects.create(follower=user_profile, followee=profile)


def my_profile(request, profile):
    form = ProfileModelForm(request.POST or None,
                            request.FILES or None,
                            instance=profile)

    if request.method == 'POST':
        if form.is_valid():
            if 'image' in request.FILES:
                image = base64.b64encode(request.FILES['image'].read())
                form.fields['avatar'].initial = upload_file(image)
                profile.avatar = form.fields['avatar'].initial
                profile.save()
            elif 'submit-default' in request.POST:
                profile.avatar = 'https://i.ibb.co/tKtFPgr/blank-profile-picture-g9a1ddb035-640.png'

            form.save()
    return form


def profile_view(request, profile_id):
    user_profile = None
    profile = Profile.objects.get(id=profile_id)
    profile_owner = False

    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user=request.user)

    form = None
    if user_profile and profile == user_profile:
        form = my_profile(request, profile)
        profile_owner = True
    elif user_profile:
        follows(request, profile, user_profile)
        profile_owner = False

    context = {
        'form': form,
        'profile': profile,
        'profile_owner': profile_owner,
        'is_followers': Follow.objects.filter(follower=user_profile, followee=profile),
    }

    return render(request, 'profiles/profile.html', context)


def profiles_list_view(request):
    try:
        search_filter = request.GET['search']
    except:
        search_filter = ''
    print(request.GET)
    profiles = Profile.objects.all()
    profiles = profiles.filter(user__username__contains=search_filter) | \
               profiles.filter(first_name__contains=search_filter) | \
               profiles.filter(last_name__contains=search_filter)

    paginator = Paginator(profiles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }

    return render(request, 'profiles/profiles_list.html', context)

profiles/templates/profiles/profile.html
{% extends 'general/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="rounded-top text-white d-flex flex-row align-items-end headline">
        <div class="ms-4 mt-5 d-flex flex-column headline_avatar-and-button">
            <img src="{{ profile.avatar }}"
                 alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 avatar">
        </div>
        <div class="ms-3 headline-personal-info">
            <h5>{{ profile.first_name }} {{ profile.last_name }}</h5>
            <p>@{{ profile.user.username }}</p>
        </div>
    </div>

    <div class="p-4 text-black headline-info">
        <div class="row">
            <div class="col-auto">
                {% if profile_owner %}
                    <button type="button"  data-toggle="modal" data-target="#info-update" class="btn btn-outline-dark btn-edit-profile" data-mdb-ripple-color="dark">
                        Edit profile
                    </button>
                {% elif user.is_authenticated %}
                    <form action="" class='btn-edit-profile' method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-dark w-100" data-mdb-ripple-color="dark">
                            {% if is_followers %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="col d-flex justify-content-end text-center py-1">
                <div class="px-3">
                    <p class="mb-1 h5">{{ profile.get_followers_number }}</p>
                    <p class="small text-muted mb-0">Followers</p>
                </div>
                <div class="px-3">
                    <p class="mb-1 h5">{{ profile.get_following_number }}</p>
                    <p class="small text-muted mb-0">Following</p>
                </div>
            </div>
        </div>
    </div>

    <hr class="w-100%">
    <h3 class="mt-1 ml-2">Collection</h3>
    <div class="row d-flex justify-content-around">
        <div class="mb-1 col-sm-4 card-body p-4 text-black d-flex justify-content-around">
            <a href='{% url 'library:book-list' collection_id=profile.get_bookshelf.id %}' class="btn-collection btn" data-mdb-ripple-color="dark">
                <div class="p-4">
                    <p class="font-weight-bold mb-0">Bookshelf </p>
                    <hr>
                    <p class="font-italic mb-0">{{ profile.get_my_books_number }}
                        {% if profile.get_my_books_number == 1%}
                            book
                        {% else %}
                            books
                        {% endif %}
                    </p>
                </div>
            </a>
        </div>
        <div class="mb-1 col-sm-4 card-body p-4 text-black d-flex justify-content-around">
            <a href='{% url 'library:book-list' collection_id=profile.get_wish_list.id %}' class="btn-collection btn" data-mdb-ripple-color="dark">
                <div class="p-4">
                    <p class="font-weight-bold mb-0">Wish List</p>
                    <hr>
                    <p class="font-italic mb-0">{{ profile.get_wish_list_books_number }}
                        {% if profile.get_wish_list_books_number == 1%}
                            book
                        {% else %}
                            books
                        {% endif %}
                    </p>
                </div>
            </a>
        </div>
        <div class="mb-1 col-sm-4 card-body p-4 text-black d-flex justify-content-around">
            <a href='{% url 'library:book-list' collection_id=profile.get_favorites.id %}' class="btn-collection btn" data-mdb-ripple-color="dark">
                <div class="p-4">
                    <p class="font-weight-bold mb-0">Favorites books </p>
                    <hr>
                    <p class="font-italic mb-0">{{ profile.get_favorites_books_number }}
                        {% if profile.get_favorites_books_number == 1 %}
                            book
                        {% else %}
                            books
                        {% endif %}
                    </p>
                </div>
            </a>
        </div>
    </div>

    <hr class="w-100%">
    <h3 class="mt-1 ml-2">Followers </h3>
    <div class="row d-flex justify-content-center">
        <div class="MultiCarousel" data-items="1,2,3,4" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner d-flex align-items-center justify-content-center">
                {% for follower in profile.followers.all %}
                <div class="item">
                    <div class="pad15">
                        <img src="{{ follower.profile.avatar }}" class="img-fluid img-thumbnail mt-2 mb-2 avatar" >
                        <div class="h-100">
                            <h6 class="mb-0 mt-0">{{ follower.profile.first_name }} {{ follower.profile.last_name }}</h6>
                            <span>@{{ follower.username }}</span>
                            <div class="button mt-2 d-flex flex-row align-items-center">
                                <a href="{% url 'profiles:profile' profile_id=follower.profile.pk %}" class=" w-100">
                                    <button class="btn btn-sm btn-see-profile btn-outline-primary w-100">See profile</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
	</div>

    <hr class="w-100%">
    <h3 class="mt-1 ml-2">Following </h3>
    <div class="row d-flex justify-content-center">
        <div class="MultiCarousel" data-items="1,2,3,4" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner d-flex align-items-center justify-content-center">
                {% for follower in profile.following.all %}
                <div class="item">
                    <div class="pad15">
                        <img src="{{ follower.profile.avatar }}" class="img-fluid img-thumbnail mt-2 mb-2 avatar" >
                        <div class="h-100">
                            <h6 class="mb-0 mt-0">{{ follower.profile.first_name }} {{ follower.profile.last_name }}</h6>
                            <span>@{{ follower.username }}</span>
                            <div class="button mt-2 d-flex flex-row align-items-center">
                                <a href="{% url 'profiles:profile' profile_id=follower.profile.pk %}" class=" w-100">
                                    <button class="btn btn-sm btn-see-profile btn-outline-primary w-100">See profile</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
	</div>
<div class="modal modal-xlg " id="info-update"
     role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">

    <div class="modal-dialog modal-xlg ">
        <div class="modal-content">
                <!-- Modal root -->
            <div class="m-header">
                <button class="close" data-dismiss="modal">
                    ×
                </button>

            </div>
            <div class="modal-body">
                <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="row align-items-center justify-content-center">
                        <div class="description col-sm-7 info-update">

                            {% if form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    {% for error in form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}

                            {% for field in form.visible_fields %}
                                {% if field.id_for_label != 'id_avatar' and field.id_for_label != 'id_image' %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        {% if form.is_bound %}
                                            {% if field.errors %}
                                                {% render_field field class="form-control is-invalid" %}
                                                {% for error in field.errors %}
                                                    <div class="invalid-feedback">
                                                        {{ error }}
                                                    </div>
                                                {% endfor %}
                                            {% else %}
                                                {% render_field field class="form-control is-valid" %}
                                            {% endif %}
                                        {% else %}
                                            {% render_field field class="form-control" %}
                                        {% endif %}
                                        {% if field.help_text %}
                                            <small class="form-text text-muted">{{ field.help_text }}</small>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}

                            <button class="file-upload-btn mt-2" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>
                            <input class="file-upload-input" type='file' name="image" id="id_image" onchange="readURL(this);" accept="image/*" />

                            <button type="button" onclick="removeUpload()" class="mt-2 remove-btn">Set default</button>
                        </div>

                        <div class="image content align-items-center col-sm-3 mt-2 info-update">
                            <div class="image-preview align-items-center justify-content-center">
                                <div class="actual-image avatar mr-ml-autor">
                                    <img class="avatar-preview-style" src="{{ profile.avatar }}" alt="your image" />
                                </div>
                                <div class="uploaded-image mr-2">
                                    <img class="file-upload-image avatar-preview-style" src="#" alt="your image" />
                                </div>
                                <div class="default-image mr-ml-auto">
                                    <img class="avatar-preview-style" src="https://i.ibb.co/tKtFPgr/blank-profile-picture-g9a1ddb035-640.png" alt="your image" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row align-items-center justify-content-center">
                        <div class="modal-footer border-top-0 d-flex justify-content-center" style="width:100%">
                            <button type="submit"  class="btn btn-success update-profile-btn">Submit</button>
                        </div>
                        <div class="modal-footer border-top-0 d-flex justify-content-center" style="width:100%">
                            <button type="submit"  name='submit-default', class="btn btn-success submit-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}