BookCollection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from profiles import urls as profiles_urls
from library import urls as library_urls
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(profiles_urls, namespace='profiles')),
    path('library/', include(library_urls, namespace='library')),
    path('', home_view),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),

]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import book_create_or_update_view, collection_view, book_view, book_delete

app_name = 'library'

urlpatterns = [
    path('book-create/', book_create_or_update_view, name='book-create'),
    path('book-update/<str:book_id>', book_create_or_update_view, name='book-update'),
    path("select2/", include("django_select2.urls")),
    path("collection/<str:collection_id>/", collection_view, name='book-list'),
    path("book/<collection_id>/<str:book_id>/", book_view, name='book'),
    path("book-delete/<collection_id>/<str:book_id>/", book_delete, name='book-delete')
]

profiles/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from .views import profile_view, profiles_list_view

app_name = 'profiles'

urlpatterns = [
    path('profile/<profile_id>/', profile_view, name='profile'),
    path('', profiles_list_view, name='profile-list'),
]

library/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget

from .models import Book, Author, PurchaseInfo, Series, Publisher, Collection, COLLECTION_CHOICES
from django.forms import formset_factory


class CollectionModelForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = ('name', )


class DateInput(forms.DateInput):
    input_type = 'date'


class BookModelForm(forms.ModelForm):
    image = forms.FileField(required=False)
    collections = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple, choices=COLLECTION_CHOICES)

    class Meta:
        model = Book
        fields = ('title', 'volume', 'publication_date', 'description', 'identifier',
                  'page_count', 'height', 'width', 'thickness', 'cover', 'categories',
                  'rating', 'notes')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'notes': forms.Textarea(attrs={'rows': 4}),
            'categories': forms.CheckboxSelectMultiple,
            'rating': forms.RadioSelect,
            'publication_date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(BookModelForm, self).__init__(*args, **kwargs)

        self.fields['cover'].required = False


class AuthorModelForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('name',)


class PurchaseModelForm(forms.ModelForm):
    class Meta:
        model = PurchaseInfo
        fields = ('purchase_date', 'price',)
        widgets = {
            'purchase_date': DateInput(),
        }


class SeriesModelForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ('name',)


class PublisherModelForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ('name',)


class AuthorDTOForm(forms.Form):
    name = forms.CharField(max_length=100)


AuthorDTOFormset = formset_factory(AuthorDTOForm, extra=1)

library/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.core.paginator import Paginator
from django_filters import  filters
from .forms import AuthorDTOFormset
from .utils import search_in_book_info, order_by, filter
from profiles.models import Profile
from profiles.views import upload_file
from .forms import CollectionModelForm, BookModelForm, AuthorModelForm, SeriesModelForm, PurchaseModelForm, PublisherModelForm
from .models import Book, Publisher, Author, PurchaseInfo, Series, Collection, CATEGORY_CHOICES
from .filters import BookFilter
from django.forms.models import model_to_dict
import base64


def add_author_to_list(request, author_name):
    if 'authors' not in request.session:
        request.session['authors'] = []

    authors = request.session['authors']
    if author_name not in authors:
        authors.append(author_name)
        request.session['authors'] = authors


def remove_author_from_list(request, author_name):
    authors = request.session['authors']
    if author_name in authors:
        authors.remove(author_name)
        request.session['authors'] = authors


def get_authors(request):
    if 'authors' not in request.session:
        request.session['authors'] = []

    return request.session['authors']


def are_forms_valid(forms):
    for form in forms:
        if not form.is_valid():
            return False

    return True


def book_create_or_update_view(request, book_id=None):
    profile = Profile.objects.get(user=request.user)

    if book_id:
        book = Book.objects.get(id=book_id)
        publisher = book.publisher
        series = book.series
        purchase = book.purchase_info
        collections = {}
        collections = book.collection.all().values('name')[0]['name']
        if 'authors' not in request.session:
            for author in book.authors.all():
                add_author_to_list(request, author.name)
    else:
        book = None
        publisher = None
        series = None
        purchase = None
        collections = None

    book_form = BookModelForm(request.POST or None, request.FILES or None, instance=book, prefix='book')
    authors_form = AuthorModelForm(request.POST or None, request.FILES or None, prefix='author')
    publisher_form = PublisherModelForm(request.POST or None, request.FILES or None, instance=publisher, prefix='publisher')
    purchase_form = PurchaseModelForm(request.POST or None, request.FILES or None, instance=purchase, prefix='purchase')
    series_form = SeriesModelForm(request.POST or None, request.FILES or None, instance=series, prefix='series')
    forms = [purchase_form, publisher_form, series_form]
    book_form.fields['collections'].initial = collections

    if request.method == 'POST':
        if 'remove-author' in request.POST and authors_form.is_valid():
            author = request.POST.get('remove-author')
            remove_author_from_list(request, author)

        elif 'add-author' in request.POST and authors_form.is_valid():
            author = request.POST.get('author-name')
            add_author_to_list(request, author)

        elif ('submit' in request.POST or 'submit-default' in request.POST) and book_form.is_valid() and are_forms_valid(forms):
            book_form.save()
            book = book_form.instance

            if 'book-image' in request.FILES:
                image = base64.b64encode(request.FILES['book-image'].read())
                book.cover = upload_file(image)
                print(book.cover)

            elif 'submit-default' in request.POST:
                book.cover = 'https://i.ibb.co/s2THm06/no-image-icon-23480.jpg'
                print(book.cover)

            book.collection.clear()
            for collection in request.POST.getlist('book-collections'):
                collection = profile.get_collection(collection)
                collection.books.add(book)
                collection.owner = profile
                collection.save()

            book.authors.clear()
            authors = get_authors(request)
            existing_authors = profile.get_all_authors()

            for author in authors:
                if author not in existing_authors:
                    author1 = Author.objects.create(name=author)
                else:
                    author1 = profile.get_author(author)

                book.authors.add(author1)

            if request.POST.get('publisher-name') != '':
                publisher = profile.get_publisher(request.POST.get('publisher-name'))

                if publisher is None:
                    publisher = publisher_form.save()

                book.publisher = publisher
            else:
                book.publisher = None

            if request.POST.get('series-name') != '':
                series = profile.get_series(request.POST.get('series-name'))
                if series is None:
                    series = series_form.save()

                book.series = series
            else:
                book.series = None

            if request.POST.get('purchase-purchase_date') != '' and request.POST.get('purchase-purchase_price') != '':
                purchase = purchase_form.save()
                book.purchase_info = purchase
            else:
                purchase_form = None

            book.save()

            request.session.delete('authors')
            return redirect("library:book", book_id=book.id, collection_id=collection.id)

    authors = get_authors(request)

    context = {
        'authors_form': authors_form,
        'profile': profile,
        'authors': authors,
        'book_form': book_form,
        'series_form': series_form,
        'publisher_form': publisher_form,
        'purchase_form': purchase_form,
    }

    return render(request, 'library/book_create.html', context)


def collection_view(request, collection_id):

    books = Collection.objects.get(id=collection_id).books.all()
    collection = Collection.objects.get(id=collection_id)

    filterset = BookFilter(request.GET, books)
    books = filter(books, request.GET)

    books = search_in_book_info(books, request.GET)
    print(books)
    books = order_by(books, request.GET)

    paginator = Paginator(books.distinct(), 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'filterset': filterset,
        'collection': collection,
        'category_choices': list(next(zip(*CATEGORY_CHOICES)))
    }

    return render(request, 'library/collection.html', context)


def book_view(request, collection_id, book_id):
    book = Book.objects.get(pk=book_id)
    collection = Collection.objects.get(id=collection_id)
    owner = Profile.objects.get(id=collection.owner_id).user
    context = {
        'book': book,
        'owner': owner,
        'collection': collection,
    }

    return render(request, 'library/book.html', context)


def book_delete(request, book_id, collection_id):
    book = Book.objects.get(id=book_id)
    collection = Collection.objects.get(id=collection_id)
    collection.books.remove(book)

    if not book.collection.all():
        book.delete()

    return redirect("library:book-list", collection_id=collection_id)

library/templates/library/book.html
{% extends 'general/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="form-row mr-2 ml-2  mt-2">
        <a href="{% url 'profiles:profile' profile_id=owner.id %}"> {{ owner.username }} </a>  &raquo;
        <a href="{% url 'library:book-list' collection_id=collection.id %}"> {{ collection.name }} </a> &raquo;
        {{ book.title }}
    </div>
    <div class="form-row mt-2  mt-4 content justify-content-center">
        <div class="image content justify-content-center align-items-center col-sm-1 mt-2 info-update">
            <div class="image-preview align-items-center justify-content-center">
                <div class="actual-image mr-ml-autor">
                    <img class="cover-preview-style" src="{{ book.cover }}" alt="your image" />
                </div>
            </div>
        </div>
        <div class="col-sm-8 mr-6">
            <div class="form-row mt-2 bg-dark text-white">
                <div class="col ml-2 mr-2 mb-0 form-group">
                    <h2 class="w-100"> {{ book.title }} </h2>
                </div>
                <div class="form-group mt-auto mb-auto">
                {% if user.is_authenticated and user == owner%}
                    <div class="col--md-auto d-flex justify-content-end p-2 mt-auto mb-auto form-group">
                        <a href="{% url 'library:book-update' book_id=book.id %}" book_id=book.id collection_id=collection.id %}">
                            <button type="button" class="btn btn-info">Update</button>
                        </a>
                    </div>
                    <div class="col-md-auto d-flex justify-content-end p-2 mt-auto mb-auto form-group">
                        <a href="{% url 'library:book-delete' book_id=book.id collection_id=collection.id %}">
                            <button type="button" class="btn btn-info">Delete</button>
                        </a>
                    </div>
                {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="col-sm ml-2 mr-2 form-group">
                    <h5 class="mt-2">{%  for author in book.authors.all%}
                        <a href="{% url 'library:book-list' collection_id=collection.id%}?authors={{ author.pk }}"> {{ author}}, </a>
                    {% endfor %}</h5>
                </div>
            </div>
        <hr class="w-100">
            <div class="form-row mt-2">
                <div class="col-sm ml-2 mr-2 form-group">
                    <h6 class="font-weight-bold">Series:</h6>
                    {% if book.series%}
                        <h6>
                            <a href="{% url 'library:book-list' collection_id=collection.id%}?series={{ book.series.pk }}">{{ book.series }}</a>
                            {% if book.volume %}
                                [{{ book.volume }}]
                            {% endif %}
                        </h6>
                    {% else %}
                        <h6>---</h6>
                    {% endif %}
                </div>
            </div>
        <hr class="w-100">
            <div class="form-row mt-2">
                <div class="col-sm ml-2 mr-2 form-group">
                    <h6 class="font-weight-bold">Rating:</h6>
                    {% if book.rating is not None%}
                        <h6>{{ book.rating }}/5</h6>
                    {% else %}
                        <h6>---</h6>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <hr clas="w-100">

    {% if book.description %}
        <div class="form-row mt-2 mr-4 ml-4  mt-4">
            <h6 class="font-weight-bold">Description:</h6><h6>{{ book.description }} </h6>
        </div>
        <hr>
    {% endif %}
    {% if book.categories %}
        <div class="form-row mt-2 ml-4 mr-4  mt-4">
        <div class="col">
            <h6 class="font-weight-bold">Categories:</h6>
            <div class="row ml-1 mr-1">
            {% for category in book.categories %}
            <a href="{% url 'library:book-list' collection_id=collection.id %}?categories={{ category }}">
                <h6>{{ category }}, </h6>
            </a>
            {% endfor %}
        </div>
        </div>
        </div>
        <hr>
    {% endif %}

    {% if book.publisher or book.identifier %}
        <div class="form-row mt-2 ml-4 mr-4">
            {% if book.publisher %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">Publisher:</h6>
                    <a href="{% url 'library:book-list'  collection_id=collection.id %}?publisher={{ book.publisher.pk }}">
                        <h6>{{ book.publisher }}</h6>
                    </a>
                </div>
            {% endif %}
            {% if book.identifier %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">ISBN:</h6><h6>{{ book.identifier }}</h6>
                </div>
            {% endif %}
        </div>
        <hr>
    {% endif %}

    {% if book.page_count or book.width or book.height or book.thickness %}
        <div class="form-row mt-2 ml-4 mr-4">
            {% if book.page_count %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">Page:</h6><h6>{{ book.page_count }}</h6>
                </div>
            {% endif %}
            {% if book.width or book.height or book.thickness %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">
                        Dimension[ {% if book.width %} width x {% endif %}{% if book.height %} height x {% endif %}{% if book.thickness %} x thickness]{% endif %}:
                    </h6><h6>
                        {% if book.width %} book.width x {% endif %}{% if book.height %} book.height x {% endif %}{% if book.thickness %} x book.thickness]{% endif %}
                </h6>
                </div>
            {% endif %}
        </div>
        <hr>
    {% endif %}

    {% if book.purchase_info %}
        <div class="form-row mt-2 ml-4 mr-4">
            {% if book.purchase_info.purchase_date %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">Purchase date:</h6><h6>{{ book.purchase_info.purchase_date }}</h6>
                </div>
            {% endif %}
            {% if book.purchase_info.price %}
                <div class="col-sm form-group">
                    <h6 class="font-weight-bold">Purchase price:</h6><h6>{{ book.purchase_info.price}}</h6>
                </div>
            {% endif %}
        </div>
        <hr>
    {% endif %}

    {% if book.notes %}
        <div class="form-row mt-2 ml-4 mr-4  mt-4">
            <h6 class="font-weight-bold">Notes:</h6> <h6>{{ book.notes }} </h6>
        </div>
    {% endif %}

{% endblock %}