BookCollection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
from profiles import urls as profiles_urls
from library import urls as library_urls
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(profiles_urls, namespace='profiles')),
    path('library/', include(library_urls, namespace='library')),
    path('', home_view),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),

]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import book_create_or_update_view, collection_view, book_view, book_delete

app_name = 'library'

urlpatterns = [
    path('book-create/', book_create_or_update_view, name='book-create'),
    path('book-update/<str:book_id>', book_create_or_update_view, name='book-update'),
    path("select2/", include("django_select2.urls")),
    path("collection/<str:collection_id>/", collection_view, name='book-list'),
    path("book/<collection_id>/<str:book_id>/", book_view, name='book'),
    path("book-delete/<collection_id>/<str:book_id>/", book_delete, name='book-delete')
]

profiles/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from .views import profile_view, profiles_list_view

app_name = 'profiles'

urlpatterns = [
    path('profile/<profile_id>/', profile_view, name='profile'),
    path('', profiles_list_view, name='profile-list'),
]

templates/general/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <link rel="icon" href="{% static '/images/favicon.ico'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="{% static '/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/my_profile.css' %}">
    <link rel="stylesheet" href="{% static '/general.css' %}">
    <link rel="stylesheet" href="{% static '/library.css' %}">


</head>

<body>
    {%  include 'general/navbar.html' %}
    <section class="h-100 gradient-custom-2">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-lg-9 col-xl-12">
                    <div class="card">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static '/library.js' %}"></script>
<script src="{% static '/profile.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src="https://unpkg.com/htmx.org@1.5.0"
        integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI"
        crossorigin="anonymous"></script>
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</html>

templates/general/foot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/general/home.html
{% extends 'general/base.html' %}

{% block content %}
    <h1> STRONA NIE GdOTOWA </h1>
{% endblock %}

templates/general/login.html
{% extends "general/base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

templates/general/navbar.html
{% load static %}
<div class="header-blue">
    <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
        <div class="container">
            <div class="navbar-title">BookCollection</div>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <form class="form-inline mr-auto" action={% url 'profiles:profile-list'%} method="get" >
                    <div class="form-group">
                        <label for="search-field">
                            <i class="fa fa-search"></i>
                        </label>
                        <input class="form-control search-field" type="search" name="search" id="search-field" placeholder="Find user">
                    </div>
                </form>
                {% if not user.is_authenticated %}
                    <span class="navbar-text"> <a href="http://127.0.0.1:8000/accounts/login/" class="login">Log In</a></span><a class="btn btn-light action-button" role="button" href="http://127.0.0.1:8000/accounts/signup/">Sign Up</a></div>
                {% else %}
                    <span class="navbar-text mr-3"> <a href="{% url 'library:book-create' %}" class="logout">Add book</a></span>
                    <span class="navbar-text mr-3"> <a href="{% url 'profiles:profile' profile_id=request.user.id %}" class="logout">My profile</a></span>
                   <span class="navbar-text"> <a href="http://127.0.0.1:8000/logout" class="logout">Logout</a></span>
                {% endif %}
            </div>

    </nav>
</div>